setwd("/media/mic0331/Data/Data Analysis/Courses/Edx/MITx: 15.071x The Analytics Edge")
WHO = read.csv("./dataset/WHO.csv")
str(WHO)
plot(WHO$GNI, WHO$FertilityRate)
install.packages("ggplot2")
library(ggplot2)
scatterplot = ggplot(WHO, aes(x = GNI, y = FertilityRate))
scatterplot + geom_point()
scatterplot + geom_line()
scatterplot + geom_point(color="blue", size=3, shape=17)
scatterplot + geom_point(color="darkred", size=3, shape=8)
fertilityGNIplot = scatterplot + geom_point(color="darkred", size=3, shape=8) + ggtitle("Fertility Rate vs. Gross National Income")
pdf("myplot.pdf")
print(fertilityGNIplot)
dev.off()
ggplot(WHO, aes(x = GNI, y = FertilityRate, color = Region)) + geom_point()
ggplot(WHO, aes(x = GNI, y = FertilityRate, color = LifeExpectancy)) + geom_point()
ggplot(WHO, aes(x = FertilityRate, y = Under15)) + geom_point()
ggplot(WHO, aes(x = log(FertilityRate), y = Under15)) + geom_point()
model = lm(Under15 ~ log(FertilityRate), data = WHO)
summary(model)
ggplot(WHO, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method = lm, level = .99)
ggplot(WHO, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method = lm, se = FALSE)
ggplot(WHO, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method = lm, se = FALSE, color = "orange")
ggplot(WHO, aes(x = FertilityRate, y = Under15, color = Region)) + geom_point()

mvt = read.csv("./dataset/mvt.csv", stringsAsFactors = FALSE)
str(mvt)
mvt$Date = strptime(mvt$Date, format = "%m/%d/%y %H:%M")
mvt$Weekday = weekdays(mvt$Date)
mvt$Hour = mvt$Date$hour
str(mvt)
WeekdayCounts = as.data.frame(table(mvt$Weekday))
str(WeekdayCounts)
library(ggplot2)
ggplot(WeekdayCounts, aes(x = Var1, y = Freq)) + geom_line(aes(group=1))
WeekdayCounts$Var1 = factor(WeekdayCounts$Var1, ordered=TRUE, levels=c("dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"))
ggplot(WeekdayCounts, aes(x = Var1, y = Freq)) + geom_line(aes(group=1)) + xlab("Day of the Week") + ylab("Total Motor vehicle Threets")
ggplot(WeekdayCounts, aes(x = Var1, y = Freq)) + geom_line(aes(group=1), linetype=2)
ggplot(WeekdayCounts, aes(x = Var1, y = Freq)) + geom_line(aes(group=1), alpha=.3)
table(mvt$Weekday, mvt$Hour)
DayHourCounts = as.data.frame(table(mvt$Weekday, mvt$Hour))
str(DayHourCounts)
DayHourCounts$Hour = as.numeric(as.character(DayHourCounts$Var2)) # factor to numeric
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_line(aes(group=Var1, color=Var1, size=2))
DayHourCounts$Var1 = factor(WeekdayCounts$Var1, ordered=TRUE, levels=c("lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"))
ggplot(DayHourCounts, aes(x = Hour, y=Var1)) + geom_tile(aes(fill = Freq))
ggplot(DayHourCounts, aes(x = Hour, y=Var1)) + geom_tile(aes(fill = Freq)) + scale_fill_gradient(name = "total MV Thefts") + theme(axis.title.y = element_blank())
ggplot(DayHourCounts, aes(x = Hour, y=Var1)) + geom_tile(aes(fill = Freq)) + scale_fill_gradient(name = "total MV Thefts", low="white", high = "red") + theme(axis.title.y = element_blank())

install.packages("maps")
install.packages("ggmap")
library(maps)
library(ggmap)
chicago = get_map(location = "chicago", zoom=11)
ggmap(chicago)
ggmap(chicago) + geom_point(data = mvt[1:100,], aes(x = Longitude, y = Latitude))
LatLonCount = as.data.frame(table(round(mvt$Longitude,2), round(mvt$Latitude,2)))
str(LatLonCount)
LatLonCount$Long = as.numeric(as.character(LatLonCount$Var1))
LatLonCount$Lat = as.numeric(as.character(LatLonCount$Var2))
ggmap(chicago) + geom_point(data=LatLonCount, aes(x=Long, y = Lat, color = Freq, size = Freq))
ggmap(chicago) + geom_point(data=LatLonCount, aes(x=Long, y = Lat, color = Freq, size = Freq)) + scale_color_gradient(low="yellow", high="red")
ggmap(chicago) + geom_tile(data=LatLonCount, aes(x=Long, y=Lat, alpha = Freq), fill="red")
LatLonCounts2 <- subset(LatLonCount, LatLonCount$Freq > 0)
ggmap(chicago) + geom_tile(data=LatLonCounts2, aes(x=Long, y=Lat, alpha = Freq), fill="red")
1638-686

murders = read.csv("./dataset/murders.csv")
str(murders)
statesMap = map_data("state")
str(statesMap)
library(ggplot2)
ggplot(statesMap, aes(x=long, y=lat, group=group)) + geom_polygon(fill="white", color="black")
murders$region = tolower(murders$State)
murderMap = merge(statesMap, murders, by="region")
str(murderMap)
ggplot(murderMap, aes(x=long, y=lat, group=group, fill=Murders)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend")
ggplot(murderMap, aes(x=long, y=lat, group=group, fill=Population)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend")
murderMap$MurderRate = murderMap$Murders/murderMap$Population*100000
ggplot(murderMap, aes(x=long, y=lat, group=group, fill=MurderRate)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend")
ggplot(murderMap, aes(x=long, y=lat, group=group, fill=MurderRate)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend", limits=c(0,10))

ggplot(murderMap, aes(x = long, y = lat, group=group, fill = GunOwnership)) + geom_polygon(color="black") + scale_fill_gradient(low = "black", high = "red", guide="legend")



